# Generated by Django 2.1.1 on 2019-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_url', models.FileField(upload_to='txt')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
